glooMgmtServer:
  enabled: true
  ports:
    healthcheck: 8091
prometheus:
  enabled: true
redis:
  deployment:
    enabled: true
glooUi:
  enabled: true
  serviceType: LoadBalancer
glooAgent:
  enabled: true
  relay:
    serverAddress: gloo-mesh-mgmt-server:9900
    authority: gloo-mesh-mgmt-server.gloo-mesh
extAuthService:
  enabled: true
  extAuth: 
    apiKeyStorage: 
      name: redis
      enabled: true
      config: 
        connection: 
          host: redis.gloo-mesh-addons:6379
      secretKey: ThisIsSecret
rateLimiter:
  enabled: true
telemetryGateway:
  enabled: true
  service:
    type: LoadBalancer
telemetryCollector:
  enabled: true
  config:
    exporters:
      otlp:
        endpoint: gloo-telemetry-gateway.gloo-mesh.svc:4317
telemetryCollectorCustomization:
  extraExporters:
    logging/mesh:
      verbosity: normal
  extraPipelines:
    logs/accesslogs:
      receivers:
        - otlp
      processors: [batch, memory_limiter]
      exporters: 
        - logging/mesh
        - otlp
telemetryGatewayCustomization:
  env:
    - name: DT_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: dynatrace
          key: dynatrace_oltp_url
    - name: DT_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: dynatrace
          key: dt_api_token
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  extraExporters:
    logging/mesh:
      verbosity: normal # detailed
    otlphttp/dt:
      endpoint: https://ikq13173.apps.dynatrace.com/api/v2/otlp
      headers:
        Authorization: "Api-Token dt0c01.HMDQQMGHBK656SSJZB5FDQSG.DEVC2RYT5OAIC2ZURSU33FQS6IRVTQEKHFAMDPFYTT5IKN3OUZ6HY35TJJWLL3DP"
  # extraProcessors:
  #   resource/mesh:
  #     attributes:
  #     - action: insert
  #       key: loki.format
  #       value: json
  #     - action: insert
  #       key: loki.resource.labels
  #       value: namespace, instance
  #   attributes/mesh:
  #     actions:
  #       - action: insert
  #         key: loki.attribute.labels
  #         value: istio_client_type
  extraPipelines:
    logs/dt:
      receivers: [otlp]
      processors:
        - batch
        # - resource/mesh
        # - attributes/mesh
      exporters: 
        - otlphttp/dt
        - logging/mesh
    traces/dt: 
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlphttp/dt
        - logging/mesh
